name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DISPLAY: :99

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
          sudo apt update
          sudo apt install -y xcb xvfb 

    - name: Start Xvfb
      run: |
         Xvfb :99 -screen 0 1920x1080x24 &
         sleep 3 
    
    - name: Build package
      run: pip install .
    
    - name: Run package
      run: lector
